---
# task file for ssh & gpg keys
- name: install
  community.general.homebrew:
    state: latest
    name:
      - gnupg
      - pinentry-mac
  when: ansible_facts['distribution'] == 'MacOSX'

- name: install
  community.general.pacman:
    state: latest
    name:
      - gnupg
      - pinentry
  when: ansible_facts['distribution'] == 'Archlinux'

- name: link agent config
  ansible.builtin.file:
    src: "{{ repo_path }}/dotfiles/gnupg/gpg-agent_macosx.conf"
    dest: "{{ home }}/.gnupg/gpg-agent.conf"
  when: ansible_facts['distribution'] == 'MacOSX'

- name: link agent config
  ansible.builtin.file:
    src: "{{ repo_path }}/dotfiles/gnupg/gpg-agent_arch.conf"
    dest: "{{ home }}/.gnupg/gpg-agent.conf" # TODO: ensure path
  when: ansible_facts['distribution'] == 'Archlinux'

- name: ssh directory
  ansible.builtin.file:
    path: "{{ home }}/.ssh"
    state: directory
    mode: 755

- name: import ssh keys
  ansible.builtin.copy:
    remote_src: "{{ item }}"
    dest: "{{ home }}/.ssh/{{ item | basename }}"
    mode: 600
    force: no
  with_fileglob:
    - "{{ repo_path }}/private/sshkeys/*"

## gpg keys
#echo "Import gpg public keys..."
#for file in `ls $config_path/gpgkeys/*_pub.gpg`; do
#    gpg --import $file
#done
#echo "Import secret keys..."
#for file in `ls $config_path/gpgkeys/*_sec.gpg`; do
#    gpg --allow-secret-key-import --import $file
#done
## TODO write to fish function
# import ssh keys by ssh-add
