---
# task file for git
- name: install git
  community.general.homebrew:
    name: git
    state: latest
  when: ansible_facts['distribution'] == 'MacOSX'

- name: install git
  community.general.pacman:
    name: git
    state: latest
  when: ansible_facts['distribution'] == 'Archlinux'

- name: link main config
  ansible.builtin.file:
    src: "{{ repo_path }}/dotfiles/git/config"
    dest: "{{ xdg.config }}/git/config"
    state: link

- name: link private config
  ansible.builtin.file:
    src: "{{ item }}"
    dest: "{{ xdg.config }}/git/{{ item | basename }}"
    state: link
  with_fileglob:
    - "{{ repo_path }}/private/git/*"

- name: ensure local entrance
  ansible.builtin.copy:
    content: ""
    dest: ~/.config/git/config_local
    mode: 0644
